### PR TITLE
Update script to support new homebrew php packages

### PR DESCRIPTION
**Pull request by endelwar**
Tested with fresh install of php 5.6, 7.1 and 7.2

### CODE REVIEW

**Comment by w00fz** [comment]
Thanks!

I wish the 7.2 current stable php wasn't so hardcoded but I'm not sure how this could be pulled from brew. Any idea?

**Comment by endelwar** [comment]
Maybe parsing output of `brew list php`?
```
/usr/local/Cellar/php/7.2.4_1/.bottle/etc/ (4 files)
/usr/local/Cellar/php/7.2.4_1/.bottle/var/log/php-fpm.log
/usr/local/Cellar/php/7.2.4_1/bin/pear
/usr/local/Cellar/php/7.2.4_1/bin/peardev
/usr/local/Cellar/php/7.2.4_1/bin/pecl
/usr/local/Cellar/php/7.2.4_1/bin/phar
/usr/local/Cellar/php/7.2.4_1/bin/phar.phar
/usr/local/Cellar/php/7.2.4_1/bin/php
/usr/local/Cellar/php/7.2.4_1/bin/php-cgi
/usr/local/Cellar/php/7.2.4_1/bin/php-config
/usr/local/Cellar/php/7.2.4_1/bin/phpdbg
/usr/local/Cellar/php/7.2.4_1/bin/phpize
/usr/local/Cellar/php/7.2.4_1/homebrew.mxcl.php.plist
/usr/local/Cellar/php/7.2.4_1/include/php/ (311 files)
/usr/local/Cellar/php/7.2.4_1/lib/httpd/modules/libphp7.so
/usr/local/Cellar/php/7.2.4_1/lib/php/ (15 files)
/usr/local/Cellar/php/7.2.4_1/pecl -> /usr/local/lib/php/pecl
/usr/local/Cellar/php/7.2.4_1/sbin/php-fpm
/usr/local/Cellar/php/7.2.4_1/share/man/ (8 files)
/usr/local/Cellar/php/7.2.4_1/share/php/ (159 files)
```
A simple regex can take out 7.2 from path

**Comment by endelwar** [comment]
It was simpler to check for `/usr/local/opt/php/bin/php` and get PHP_VERSION out of it, what do you think?

**Comment by w00fz** [comment]
Awesome

**Pull request merged**
