### PR TITLE
Ability to disable Apache and PHP-FPM restart

### PR DESCRIPTION
**Pull request by exequiel09**
Hi @w00fz here's the pull request. Just tell me if there's some changes to be done. thanks!

### CODE REVIEW

**Comment by w00fz** [comment]
Looking good! Thank you 👍

**Comment by exequiel09** [comment]
Will be waiting for this on the HomeBrew. Thanks @w00fz

**Comment by w00fz** [comment]
Submitted the new version to homebrew.

**Comment by exequiel09** [comment]
whoa. that was fast. thanks @w00fz. we'll just wait for homebrew to accept it.

**Pull request merged**
